-- phpMyAdmin SQL Dump
-- version 3.5.8.2
-- http://www.phpmyadmin.net
--
-- Host: sql210.epizy.com
-- Generation Time: Mar 03, 2019 at 01:37 AM
-- Server version: 5.6.41-84.1
-- PHP Version: 5.3.3

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `epiz_22901556_myBlog_HarshAgrawal`
--

-- --------------------------------------------------------

--
-- Table structure for table `blogPosts`
--

CREATE TABLE IF NOT EXISTS `blogPosts` (
  `Serial_No` int(11) NOT NULL AUTO_INCREMENT,
  `Heading` varchar(500) NOT NULL,
  `ArticleBody` mediumtext NOT NULL,
  `Date` date NOT NULL,
  `Tags` varchar(5000) NOT NULL,
  PRIMARY KEY (`Serial_No`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=42 ;

--
-- Dumping data for table `blogPosts`
--

INSERT INTO `blogPosts` (`Serial_No`, `Heading`, `ArticleBody`, `Date`, `Tags`) VALUES
(19, 'WELCOME TO MY BLOG | MY INTRODUCTION', '&lt;p&gt;Hello World ! Thanks for coming to my blog. This is my first blog post. Lemme introduce myself. My name is Harsh Agrawal. A little tech savvy teenager and an aspiring soul. I am bit of an introvert and I am in a constant battle to let go of inhibtions and become a free soul :-) I keep learning stuff whether it is academic study or my tech pursuits or my musical ones (playing guitar and singing) or learning a  language. I am an anime lover and I love to watch every kind, I find them such a creative and diverse medium. &lt;br&gt; &lt;br&gt;What will I post? It is a pretty hard question. The solution, I will not think and will post anything I feel like I should share  Yep! ;) I hope you enjoy reading my posts. &lt;/p&gt;', '0000-00-00', ''),
(39, 'TOKYO GHOUL: RE - REVIEW', '&lt;p&gt;Hiyah! Welcome to today&#039;s episode which is about Tokyo Ghoul: Re, the season that some of us had been waiting for so eagerly. This is going to be a spoiler free review.&lt;br&gt;&lt;br&gt;For those if you unaware of it, Tokyo ghoul:Re is the third season of tokyo ghoul, an action anime series which follows the story of Ken Kaneki, a nerdy guy whose life changes completely when by circumstances he turns into a ghoul. His unexpected foray into a dark world is followed through. The last episode left us on a cliffhanger and since then we have had burning questions.&lt;br&gt;&lt;br&gt;The new season seems like a lost offspring of the two seasons. I had judged by the trailer when it came that something was going to be amiss in this new season and I was right. 10 episodes have aired till now and I am commenting based upon them. &lt;br&gt;&lt;br&gt;The plot of this season seems confusing at first because of lack of link to previous season but doubts get cleared quickly. But the progression is slow and anime lack expressiveness ad before. The evil forebodings, excitement and desperation before deadly fights is lacking.\r\n	That is dramatism is lacking. Here and there you get some tingling moments but it is not as heartfelt as before.The animation on a whole was fine but was not as dazzling as before. New intersting characters came into view but some old characters didn&#039;t have their characterisitic looks. Some particulars This season felt separate from the others. The settings and style were quite different. The anime does a good job on sound design. The OP was as blissful as before ones and the chibi design in the ED was as sweet as before.&lt;br&gt;&lt;br&gt; Well, watch this season whenever you get time. It has its own plently share of awesomeness. But I will also highly recommen reading the manga becuase it is way ahead of the anime and has more characters and better plot progression.&lt;/p&gt;\r\n	&lt;iframe  src=&quot;https://www.youtube.com/embed/nytIRpgO3Z4&quot; frameborder=&quot;0&quot; allow=&quot;autoplay; encrypted-media&quot; allowfullscreen&gt;&lt;/iframe&gt;', '0000-00-00', ''),
(40, 'HIDDEN GEMS #1', '&lt;p&gt;Salut! This is the first ever article of the series &#039;HIDDEN GEMS&#039;. Through the articles titled with this same name I will be sharing interesting studd just anything like songs or games that are not so popular or mainstream but are a treal to discover. This one is about three songs that I find to be really good.\r\n	&lt;br&gt;&lt;br&gt;\r\n	&lt;/p&gt;\r\n	&lt;p&gt;1. Pirouette By Made in Heights\r\n	&lt;iframe  src=&quot;https://www.youtube.com/embed/fNjQSnTn51c&quot; frameborder=&quot;0&quot; allow=&quot;autoplay; encrypted-media&quot; allowfullscreen&gt;&lt;/iframe&gt;\r\n	&lt;p&gt;2. Chase the sunrise By Ashley Mannix&lt;/p&gt;\r\n	&lt;iframe  src=&quot;https://www.youtube.com/embed/9bSQuBN2IDU&quot; frameborder=&quot;0&quot; allow=&quot;autoplay; encrypted-media&quot; allowfullscreen&gt;&lt;/iframe&gt;\r\n	&lt;p&gt;3. Colors By VÃ‰RITÃ‰&lt;/p&gt;\r\n	&lt;iframe  src=&quot;https://www.youtube.com/embed/t7XN9pmAYzc&quot; frameborder=&quot;0&quot; allow=&quot;autoplay; encrypted-media&quot; allowfullscreen&gt;&lt;/iframe&gt;', '0000-00-00', ''),
(38, 'JAPANESE SONGS RECOMMENDATION', '&lt;p&gt;Here are all the japanese songs I listen to. My list is pretty short but each of the song is a stand out.&lt;/p&gt;\r\n	&lt;p&gt;1. Unravel By Toru Kitajima (Featured in Tokyo Ghoul)&lt;/p&gt;\r\n	&lt;iframe width=&quot;100%&quot; height=&quot;300&quot; scrolling=&quot;no&quot; frameborder=&quot;no&quot; allow=&quot;autoplay&quot; src=&quot;https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/228395743&amp;color=%23ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_comments=true&amp;show_user=true&amp;show_reposts=false&amp;show_teaser=true&amp;visual=true&quot;&gt;&lt;/iframe&gt;\r\n	&lt;p&gt;2. Don&#039;t By Nakamura Emi (Featured in Waaru Salesman New)&lt;/p&gt;\r\n	&lt;iframe  src=&quot;https://www.youtube.com/embed/CicnGW43Ukw&quot; frameborder=&quot;0&quot; allow=&quot;autoplay; encrypted-media&quot; allowfullscreen&gt;&lt;/iframe&gt;\r\n	&lt;p&gt;3. Euterpe By Egoist (Featured in Guilty Crown)&lt;/p&gt;\r\n	&lt;iframe  src=&quot;https://www.youtube.com/embed/gMU7JK0zCGE&quot; frameborder=&quot;0&quot; allow=&quot;autoplay; encrypted-media&quot; allowfullscreen&gt;&lt;/iframe&gt;\r\n	&lt;p&gt;4. Blessings By Egoist (Featured in Guilty Crown) &lt;/p&gt;\r\n	&lt;iframe  src=&quot;https://www.youtube.com/embed/M_tGU3OzaVc&quot; frameborder=&quot;0&quot; allow=&quot;autoplay; encrypted-media&quot; allowfullscreen&gt;&lt;/iframe&gt;\r\n	&lt;p&gt;5. Double Down By SKY-HI&lt;/p&gt;\r\n	&lt;iframe  src=&quot;https://www.youtube.com/embed/bhk5XxE9BzM&quot; frameborder=&quot;0&quot; allow=&quot;autoplay; encrypted-media&quot; allowfullscreen&gt;&lt;/iframe&gt;\r\n	&lt;p&gt;6. Ring of Fortune By Eri Sasaki (Featured in Plastic Memories)&lt;/p&gt;\r\n	&lt;iframe  src=&quot;https://www.youtube.com/embed/OKJ3aBOt_IM&quot; frameborder=&quot;0&quot; allow=&quot;autoplay; encrypted-media&quot; allowfullscreen&gt;&lt;/iframe&gt;\r\n	&lt;p&gt;7. Merry-Go-Round By Onelifecrew (Featured in Fairy Tail )&lt;/p&gt;\r\n	&lt;iframe  src=&quot;https://www.youtube.com/embed/clFFJ9Qiacw&quot; frameborder=&quot;0&quot; allow=&quot;autoplay; encrypted-media&quot; allowfullscreen&gt;&lt;/iframe&gt;\r\n	&lt;p&gt;8. Shinzou Wou Sazzegayo By Linked Horizon (Featured in Attack On Titan)&lt;/p&gt;\r\n	&lt;iframe  src=&quot;https://www.youtube.com/embed/WAoPeG1LU1g&quot; frameborder=&quot;0&quot; allow=&quot;autoplay; encrypted-media&quot; allowfullscreen&gt;&lt;/iframe&gt;', '0000-00-00', ''),
(37, 'HORROR MOVIES RECOMMENDATION', '&lt;p&gt;1. IT (2017)&lt;br&gt;&lt;br&gt;Based on a horror novel by Stephen King, IT is an incredible movie. With top notch visual effects and consistent amusing ambience, IT is a pleaseant terror to watch.It presents to you a group of somwhat super brave kids who have to face a evil lurking within the city. With well planned course of events and consistent terror and a epic finale, IT instills in you a really good terror&lt;/p&gt;\r\n	&lt;iframe  src=&quot;https://www.youtube.com/embed/hAUTdjf9rko&quot; frameborder=&quot;0&quot; allow=&quot;autoplay; encrypted-media&quot; allowfullscreen&gt;&lt;/iframe&gt;\r\n	&lt;p&gt;2. THE CABIN IN THE WOODS (2011)&lt;br&gt;&lt;br&gt; The Cabin in the Woods is a terrific horror movie starring Chris Hemworth. Hells break upon the five-membered group went on a lttle holiday. The movie kills characters pensively and dramatically. A terrific set of climaxes and an amusing end makes it a really good watch.&lt;/p&gt;\r\n	&lt;iframe  src=&quot;https://www.youtube.com/embed/NsIilFNNmkY&quot; frameborder=&quot;0&quot; allow=&quot;autoplay; encrypted-media&quot; allowfullscreen&gt;&lt;/iframe&gt;\r\n	&lt;p&gt;3. INSIDIOUS (2010)&lt;br&gt;&lt;br&gt; Seeing one of my friend a real fan of the series, I decided to watch later the Insidous series. When I watched the first movie, I was petrified. Presenting you with a good theory on ghosts, It presents a family of four stuck in a mess. Little by little it terrifies you constantly and lands you with unexpected results till the end.&lt;/p&gt;\r\n	&lt;iframe  src=&quot;https://www.youtube.com/embed/zuZnRUcoWos&quot; frameborder=&quot;0&quot; allow=&quot;autoplay; encrypted-media&quot; allowfullscreen&gt;&lt;/iframe&gt;', '0000-00-00', ''),
(36, 'THE BEST INTRODUCTORY ONLINE COURSE FOR CS LOVERS', '&lt;p&gt;Are you pretty amused by computers, the web and all things gekky. If you are, you will love Computer Sciene. The subject delves deep into the workings of the computer and teaches you to do wonders with it. &lt;br&gt; &lt;br&gt;The one online course that gives a really good exposure with CS and its intersection and impact on other subjects is CS50 offered by Harvard. It is a first year course offered at the Harvard campus. But you can get the videos for each year at Youtube. You can also view the course at www.edx.org and even obtain a certificate. CS50 is probably a 12 week course that teaches you basics and gives you along the way so much practical knowledge. It also gives a sneak peak into other sub-fields like machine learning, web development, etc. It is taught by a super awesome teacher. It is a really dynamic course whose contents keep changing every year so things you would be learning would be the newest and best. Taking it will make you a stand out. I discovered it really later. When I was little younger, I had caught glimpse of it on my brother&#039;s laptop. And one fine day when I was exploring tutorials Ta Da! I found a video and so after that I started taking the course. But I left it in between. I am trying to get back it as soon as possible. But please believe this one course is a stand out and is completely free.&lt;/p&gt;\r\n	&lt;iframe  src=&quot;https://www.youtube.com/embed/y62zj9ozPOM&quot; frameborder=&quot;0&quot; allow=&quot;autoplay; encrypted-media&quot; allowfullscreen&gt;&lt;/iframe&gt;', '0000-00-00', ''),
(41, 'HEART BENDING AMBIENT MUSIC', '&lt;p&gt;When I was a little younger, my older brother showed me a video of a guy on YouTube producing ambient music. It was so surreal and touching to hear the beautiful melodies he made. I forgot his name and some time later I tried to find him. By the time probably my brother might have also forgotten about him so I didn&#039;t ask him. But accidentally I met the channel AmbienMusicalGenre. At that time it was not so fairly popular. I listened to one of its ambient mixes and was completely spellbound and mesmerized. Here are two of my favorites.\r\n	&lt;br&gt;&lt;br&gt;\r\n	&lt;/p&gt;\r\n	&lt;p&gt;1. Awakening of a Dream Ambient Mix&lt;/p&gt;\r\n	&lt;iframe  src=&quot;https://www.youtube.com/embed/b-b9Y_h6X7I&quot; frameborder=&quot;0&quot; allow=&quot;autoplay; encrypted-media&quot; allowfullscreen&gt;&lt;/iframe&gt;\r\n	&lt;p&gt;2. Dusk Ambient Mix&lt;/p&gt;\r\n	&lt;iframe  src=&quot;https://www.youtube.com/embed/xFWLe9_R2Fc&quot; frameborder=&quot;0&quot; allow=&quot;autoplay; encrypted-media&quot; allowfullscreen&gt;&lt;/iframe&gt;', '0000-00-00', '');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
